/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pkumar' at '22/7/16 8:08 PM' with Gradle 2.4
 *
 * @author pkumar, @date 22/7/16 8:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
