package implBaseHelloApp;


/**
* implBaseHelloApp/HelloHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/resources/Hello.idl
* Thursday, 11 January, 2018 11:51:00 AM IST
*/

abstract public class HelloHelper
{
  private static String  _id = "IDL:implBaseHelloApp/Hello:1.0";

  public static void insert (org.omg.CORBA.Any a, implBaseHelloApp.Hello that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static implBaseHelloApp.Hello extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (implBaseHelloApp.HelloHelper.id (), "Hello");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static implBaseHelloApp.Hello read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_HelloStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, implBaseHelloApp.Hello value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static implBaseHelloApp.Hello narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof implBaseHelloApp.Hello)
      return (implBaseHelloApp.Hello)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      implBaseHelloApp._HelloStub stub = new implBaseHelloApp._HelloStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static implBaseHelloApp.Hello unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof implBaseHelloApp.Hello)
      return (implBaseHelloApp.Hello)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      implBaseHelloApp._HelloStub stub = new implBaseHelloApp._HelloStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
