package implBaseHelloApp;


/**
* implBaseHelloApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/resources/Hello.idl
* Thursday, 11 January, 2018 11:51:00 AM IST
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
