package implBaseHelloApp;

/**
* implBaseHelloApp/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/resources/Hello.idl
* Thursday, 11 January, 2018 11:51:00 AM IST
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public implBaseHelloApp.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (implBaseHelloApp.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = implBaseHelloApp.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    implBaseHelloApp.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return implBaseHelloApp.HelloHelper.type ();
  }

}
