package implBaseHelloApp;


/**
* implBaseHelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/resources/Hello.idl
* Thursday, 11 January, 2018 11:51:00 AM IST
*/

public interface HelloOperations 
{
  String sayHello ();
  void shutdown ();
} // interface HelloOperations
