/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pkumar' at '4/10/16 3:46 PM' with Gradle 2.4
 *
 * @author pkumar, @date 4/10/16 3:46 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
