/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pkumar' at '10/8/16 7:22 PM' with Gradle 2.4
 *
 * @author pkumar, @date 10/8/16 7:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
