/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pkumar' at '23/1/17 6:07 PM' with Gradle 2.4
 *
 * @author pkumar, @date 23/1/17 6:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
