package za.co.sanlam;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pkumar' at '15/11/17 1:47 PM' with Gradle 2.4
 *
 * @author pkumar, @date 15/11/17 1:47 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
