/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pkumar' at '1/12/17 11:41 AM' with Gradle 2.4
 *
 * @author pkumar, @date 1/12/17 11:41 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
